### ISSUE TITLE
Plugin Manager included in LST generator.7z is outdated

### ISSUE THREAD

**Issue by Arata12** [marcussacana/StringReloads#1]
When I open the PMan.exe, it shows this error.

[image](https://i.imgur.com/wJ6qRzL.png)

And I can't install plugins.

Btw, I replaced it with the one from: 
[SacanaWrapper](https://github.com/marcussacana/SacanaWrapper/releases/tag/1.0.33)
and it worked.

**Comment by marcussacana** [comment]
Yeah, I forget, I will fix it soon, thx.

**Comment by marcussacana** [comment]
Solved
