### ISSUE TITLE
Translated string not showing

### ISSUE THREAD

**Issue by prambn** [marcussacana/StringReloads#10]
https://user-images.githubusercontent.com/76500655/148684669-781777fb-68a2-4c57-8201-1a29d490cf08.mp4

Why?? Help me, please...

| | |
| ----------- | ----------- |
| Game | [Mekurabe](https://vndb.org/v26242) |
| Engine | Softpal |

Thanks in advance.

**Comment by marcussacana** [comment]
First, everytime that you modify a .lst file, you must delete the Cache.srl, because the Cache is as the name says, A cache.
The SRL will priorize use the outdated (and untranslated) text because of the cache.
That said maybe there is a bug as well, to me check you will need set the `LogLevel=TRC` and `LogFile=true`, then send me the SRL.log to me check what is happening.

**Comment by prambn** [comment]
After that I tried to use the latest version (7.5.6 x86) and followed your suggestion to delete `Cache.srl`, but the result is still the same.

[SRL.rar](https://drive.google.com/file/d/1kUhmD230dhcaRd8418SlpRojFqcqzUn0/view?usp=sharing)

**Comment by marcussacana** [comment]
Your Strings.lst isn't translated.
![image](https://user-images.githubusercontent.com/10576957/148706370-89603048-fe11-4137-b0df-67f533390f37.png)
But anyway, Check the log
```
[TRC] Reload from:
「ぐっ……ぅうううぅっ！」
```
The original line contains 「」 and your strings.lst don't, try re-dump the strings.lst without use any filter to the quotes

**Comment by marcussacana** [comment]
Also, I saw your video now, you modified both lines, you can't do that, you must keep the first line unchanged, and the second line translated, like this:
```
女子生徒Ｂ
Name translation example
「あの方、なかなかやりますね」
「Dialog translation example」
```

**Comment by prambn** [comment]
Oh, I see.

![image](https://user-images.githubusercontent.com/76500655/148707129-16bd3827-f63d-4cf0-884f-19f762bda478.png)

![image](https://user-images.githubusercontent.com/76500655/148707155-2f57cf27-639e-4640-9b72-0ed516e0caeb.png)

Still the same.

**Comment by prambn** [comment]
[SRL.log](https://github.com/marcussacana/StringReloads/files/7836289/SRL.log)

Here is the full log.

**Comment by marcussacana** [comment]
![image](https://user-images.githubusercontent.com/10576957/148707852-154e5f71-1e23-42ab-beb4-c8c7b9a310de.png)
Delete this from the SRL.ini and setup the hook again.
I think you selected 'yes' when he asked 'can you see the translated message?' in the wrong time.

**Comment by marcussacana** [comment]
Watch this video about how you should do: https://www.youtube.com/watch?v=RAgZQBWqiJQ

**Comment by prambn** [comment]
Oh, it worked.
Thank you very much.

**Comment by prambn** [comment]
![image](https://user-images.githubusercontent.com/76500655/148708836-a0e82039-4d78-4237-9af8-2756d82108e5.png)

By the way, how to use this?
I want to reduce the font size.

![image](https://user-images.githubusercontent.com/76500655/148709162-549a64bd-21d7-4deb-a873-27343028c7d6.png)

Do I need to reinstall this tool?
I tried changing the width and height, but nothing seems to change.

**Comment by marcussacana** [comment]
Isn't all engines that is possible to change the font size.
But, if you wanna try, enable the CreateFontA/CreateFontW hooks,
then change the Width Height values and check if affect the game

**Comment by prambn** [comment]
Oh, I see. 
I'll try it another time.
Anyway, thanks for the help.
