### ISSUE TITLE
AdvHD D3D9 Wrapper Bug

### ISSUE THREAD

**Issue by wxq123qw555** [marcussacana/StringReloads#18]
I use StringReloads today
Found a problem. The error report is as follows

[INF] SRL - StringReloads v7.6.18
[INF] Created by Marcussacana
[DBG] Working Directory: G:\game\gal\WillPlus\44\StringReloads
[DBG] Initializing SRL...
[DBG] Cache not found, Building database...
[DBG] 0 Database(s) Loaded
[DBG] 0 Remap(s) Loaded
[DBG] 0 Alternative Remap(s) Loaded
[DBG] 0 Hashes Ready
[DBG] Hook "gdi32.dll->CreateFontA" Compiled; Hook: 0x0000000002D71F1E; Bypass: 0x000000000F9A0000
[DBG] Hook "gdi32.dll->CreateFontW" Compiled; Hook: 0x0000000002D71E3E; Bypass: 0x000000000F9B0000
[DBG] Hook "gdi32.dll->CreateFontIndirectA" Compiled; Hook: 0x0000000002D71E8E; Bypass: 0x000000000F9C0000
[DBG] Hook "gdi32.dll->CreateFontIndirectW" Compiled; Hook: 0x0000000002D71EDE; Bypass: 0x000000000F9D0000
[DBG] Hook "gdi32.dll->ExtTextOutA" Compiled; Hook: 0x0000000002D71F6E; Bypass: 0x000000000F9E0000
[DBG] Hook "gdi32.dll->ExtTextOutW" Compiled; Hook: 0x0000000002D71FBE; Bypass: 0x000000000F9F0000
[DBG] Hook "gdi32.dll->GetCharABCWidthsFloatA" Compiled; Hook: 0x0000000002D7200E; Bypass: 0x000000000FFA0000
[DBG] Hook "gdi32.dll->GetCharABCWidthsFloatW" Compiled; Hook: 0x0000000002D7205E; Bypass: 0x000000000FFB0000
[DBG] Hook "gdi32.dll->GetCharacterPlacementA" Compiled; Hook: 0x0000000002D720AE; Bypass: 0x000000000FFD0000
[DBG] Hook "gdi32.dll->GetCharacterPlacementW" Compiled; Hook: 0x0000000002D75196; Bypass: 0x0000000012070000
[DBG] Hook "gdi32.dll->GetGlyphOutlineA" Compiled; Hook: 0x0000000002D7539E; Bypass: 0x0000000012080000
[DBG] Hook "gdi32.dll->GetGlyphOutlineW" Compiled; Hook: 0x0000000002D753C6; Bypass: 0x0000000012090000
[DBG] Hook "gdi32.dll->GetTextExtentPoint32A" Compiled; Hook: 0x0000000002D750CE; Bypass: 0x00000000120A0000
[DBG] Hook "gdi32.dll->GetTextExtentPoint32W" Compiled; Hook: 0x0000000002D7507E; Bypass: 0x00000000120B0000
[DBG] Hook "kernel32.dll->lstrcpyA" Compiled; Hook: 0x0000000002D7534E; Bypass: 0x00000000120C0000
[DBG] Hook "kernel32.dll->lstrcpyA" Compiled; Hook: 0x0000000002D750A6; Bypass: 0x00000000120D0000
[DBG] Hook "OleAut32.dll->SysAllocString" Compiled; Hook: 0x0000000002D7511E; Bypass: 0x00000000120E0000
[DBG] Hook "Kernel32.dll->MultiByteToWideChar" Compiled; Hook: 0x0000000002D752AE; Bypass: 0x00000000120F0000
[DBG] Hook "Kernel32.dll->WideCharToMultiByte" Compiled; Hook: 0x0000000002D7520E; Bypass: 0x0000000012100000
[DBG] Hook "gdi32.dll->TextOutA" Compiled; Hook: 0x0000000002D7502E; Bypass: 0x0000000012110000
[DBG] Hook "gdi32.dll->TextOutW" Compiled; Hook: 0x0000000002D75376; Bypass: 0x0000000012130000
[DBG] Hook "OleAut32.dll->SysAllocString" Compiled; Hook: 0x0000000002D75F6E; Bypass: 0x00000000121A0000
[INF] AdvHD Engine Detected.
[INF] SRL Initialized
[TRC] Character Remaped from   to  
[ERR] [EntryPoint.cs:74(ProcessW)]
System.Exception: No Database Loaded
   in StringReloads.Engine.SRL.get_CurrentDatabase()
   in StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   in StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   in StringReloads.Engine.SRL.ProcessString(String String)
   in StringReloads.Engine.SRL.ProcessString(WCString pString)
   in StringReloads.EntryPoint.ProcessW(Void* Value)
[ERR] [EntryPoint.cs:74(ProcessW)]
System.Exception: No Database Loaded
   in StringReloads.Engine.SRL.get_CurrentDatabase()
   in StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   in StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   in StringReloads.Engine.SRL.ProcessString(String String)
   in StringReloads.Engine.SRL.ProcessString(WCString pString)
   in StringReloads.EntryPoint.ProcessW(Void* Value)
[ERR] [EntryPoint.cs:74(ProcessW)]
System.Exception: No Database Loaded
   in StringReloads.Engine.SRL.get_CurrentDatabase()
   in StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   in StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   in StringReloads.Engine.SRL.ProcessString(String String)
   in StringReloads.Engine.SRL.ProcessString(WCString pString)
   in StringReloads.EntryPoint.ProcessW(Void* Value)
[ERR] [EntryPoint.cs:74(ProcessW)]
System.Exception: No Database Loaded
   in StringReloads.Engine.SRL.get_CurrentDatabase()
   in StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   in StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   in StringReloads.Engine.SRL.ProcessString(String String)
   in StringReloads.Engine.SRL.ProcessString(WCString pString)
   in StringReloads.EntryPoint.ProcessW(Void* Value)
[ERR] [EntryPoint.cs:74(ProcessW)]
System.Exception: No Database Loaded
   in StringReloads.Engine.SRL.get_CurrentDatabase()
   in StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   in StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   in StringReloads.Engine.SRL.ProcessString(String String)
   in StringReloads.Engine.SRL.ProcessString(WCString pString)
   in StringReloads.EntryPoint.ProcessW(Void* Value)
[ERR] [EntryPoint.cs:74(ProcessW)]
System.Exception: No Database Loaded
   in StringReloads.Engine.SRL.get_CurrentDatabase()
   in StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   in StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   in StringReloads.Engine.SRL.ProcessString(String String)
   in StringReloads.Engine.SRL.ProcessString(WCString pString)
   in StringReloads.EntryPoint.ProcessW(Void* Value)
[CRI] [EntryPoint.cs:77(ProcessW)]
System.Exception: No Database Loaded
   in StringReloads.Engine.SRL.get_CurrentDatabase()
   in StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   in StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   in StringReloads.Engine.SRL.ProcessString(String String)
   in StringReloads.Engine.SRL.ProcessString(WCString pString)
   in StringReloads.EntryPoint.ProcessW(Void* Value)

**Comment by marcussacana** [comment]
Not a bug as said "No Database Loaded"
the SRL is mainly a translation tool, it just saying that can't start because no translation has found.
you can delete the cache.srl file and create a Strings.lst file in the same cache.srl directory, usually in the StringReloads directory or game root directory.

**Comment by wxq123qw555** [comment]
Thank you very much for your answer. The problem has been solved. have a nice weekend
