### ISSUE TITLE
LSTGenerator failed to extract the rld text decrypted by the exhibit engine

### ISSUE THREAD

**Issue by huazuolian** [marcussacana/StringReloads#19]
![image](https://user-images.githubusercontent.com/115382633/232416021-e5c102c4-5e86-466d-9228-fa7421c29ca4.png)
This is a text file
[Scripts.zip](https://github.com/marcussacana/StringReloads/files/11247453/Scripts.zip)

**Comment by huazuolian** [comment]
Thanks for the answer, I successfully extracted the text. Now that I've used your SacanaWrapper again to extract the rld text and modify, is there a way to change the imported back text to gbk encoding.

**Comment by marcussacana** [comment]
I'm not familiar with the GBK encoding or chinese language, usually that require patching in the engine, with SRL you can do a fake mapping using custom fonts, well, if chinese use more characters than the japanese kanjis avaiable you're in trouble then...

**Comment by huazuolian** [comment]
By modifying your RLDManager's dll import encoding to gbk, I successfully solved the Chinese display issue, thank you
