### ISSUE TITLE
SoftPAL engine issue

### ISSUE THREAD

**Issue by Arata12** [marcussacana/StringReloads#2]
I tested with 2 games and it shows this: 

No Supported Engine Detected, Auto SRL Installer Disabled
I tested:
Koi x Shin Ai Kanojo
Anata ni Koi Suru Ren'ai Recette

Koi x Shin Ai Kanojo also shows:
 Import Hook Failed: user32.dll => CreateWindowExW
Import Hook Failed: user32.dll => SetWindowPos

Anata ni Koi Suru Ren'ai Recette:
Import Hook Failed: user32.dll => CreateWindowExW

Am I doing something wrong?

SRL.ini's config is the same as The Witch's Love Diary.

**Comment by marcussacana** [comment]
open the 'dll' folder of the game, and send to me the pal.dll

**Comment by Arata12** [comment]
I included both.

[Koi x Shin Ai Kanojo](https://github.com/marcussacana/StringReloads/files/3849401/koikake-dll.zip)
[Anata ni Koi Suru Ren'ai Recette](https://github.com/marcussacana/StringReloads/files/3849403/recette-dlll.zip)

**Comment by marcussacana** [comment]
Yeah, I will need download the game to fix this, I will put in my queue

**Comment by marcussacana** [comment]
Soon™
Your request is the next game in my list.

**Comment by marcussacana** [comment]
I started analyze the game (I lost), well, isn't impossible to make the auto-install but i'm not much confident of the stability, well, this auto-install will required big changes in the SRL engine then isn't ready yet.

**Comment by marcussacana** [comment]
Instead ask the user, Looks like if the IDA PRO is installed I can use their command line to ask the IDA to generate a C file with all required informations to the SRL auto-install, this mean who make the patch will need install the IDA PRO, after the Auto-Install catch the required info you don't need more the IDA, of course the final user don't will need install the IDA or do any setup.
Well, it's just a possibility let's see...

**Comment by marcussacana** [comment]
:)
![image](https://user-images.githubusercontent.com/10576957/70006465-0d1e2a80-154c-11ea-846d-1ac936c300db.png)

**Comment by Arata12** [comment]
So, in the end, did you use the IDA PRO?

**Comment by marcussacana** [comment]
Nop, I did a method that don't need the IDA PRO, but i'm solving some bugs yet, i will publish soon

**Comment by Arata12** [comment]
Oh, I see.

**Comment by marcussacana** [comment]
The second game is working now too, Now i will do some small tests and optimization and publish the update.
![image](https://user-images.githubusercontent.com/10576957/70016548-62b00280-155f-11ea-8358-15cae36f9bae.png)

**Comment by marcussacana** [comment]
Update published, here a small tutorial how to use the auto-install now.
https://youtu.be/RAgZQBWqiJQ
test it, and if everything works close this issue plz @Arata12

**Comment by Arata12** [comment]
I just tested it, it worked well.
