### ISSUE TITLE
Translated String doesn't work

### ISSUE THREAD

**Issue by Semper-Augustus** [marcussacana/StringReloads#20]
Greeting! I've use your method to translate a game using Willplus Engine and I've got SRL.log. However the game seems running without Strings-A_00.lst, therefore the translated strings didn't display in the game. So I'm seeking for a solution. Here's the SRL.log. Could you help me find the issue that cause it? Thank you for your help!
[SRL.log](https://github.com/marcussacana/StringReloads/files/11408480/SRL.log)

**Comment by marcussacana** [comment]
This engine may have some sufixes or prefixes in the lines
![image](https://user-images.githubusercontent.com/10576957/236521554-a3779b9a-a1c0-4669-9a0c-94fde18212d7.png)
this should be the cause of the missmatch, try put the Sufix and Prefix in the SRL.ini

**Comment by marcussacana** [comment]
yes

**Comment by Semper-Augustus** [comment]
Sorry I don't get it ,could you tell me the details of the changes?

**Comment by Semper-Augustus** [comment]
ok, i get it.

**Comment by Semper-Augustus** [comment]
Well the issue have been solved. Thank you for you assistance. Btw, is there any place that I can study how to build the patch?

**Comment by marcussacana** [comment]
check examples in my specifc games repo

**Comment by Semper-Augustus** [comment]
OK, thanks
