### ISSUE TITLE
About CreateFont function

### ISSUE THREAD

**Issue by mingyue2108** [marcussacana/StringReloads#21]
Hello Marcus! May I ask how to change font of games that have no CreateFont nor CreateFontIndirect function? Thank you.

**Comment by marcussacana** [comment]
This game might be using DirectX to render the text or use pre-rendered fonts, in both cases SRL will not help, directX still possible if you change the face name if you found in the executable or some script, but in the case of pre-rendered font will need to be made an special tool

**Comment by mingyue2108** [comment]
Thank you for your reply. I'ill try changing font name in the executable file to see if it works
