### ISSUE TITLE
StringReloads question

### ISSUE THREAD

**Issue by hacker123-321** [marcussacana/StringReloads#5]
I want to translate game shin-neko ～再会した妹との新たな関係～ with StringReloads, but There was an error 
https://huyvuvi123-gmail.tinytake.com/tt/NDYwMzIzNl8xNDU5MDE2MA

**Comment by marcussacana** [comment]
change the lines in the SRL.ini
```
Log=true
LogFile=true
LogLevel=TRC
```
Then restart the game, after that the SRL will create a SRL.log file, upload that.
Also, you don't need enable the Debug mode, that are only if you want attach the SRL in the visual studio.

**Comment by hacker123-321** [comment]
Upload this?
[SRL.log](https://github.com/marcussacana/StringReloads/files/5179785/SRL.log)

**Comment by marcussacana** [comment]
```csharp
[TRC] Intercept 0x00757730 With 0x08080000
[INF] SRL Initialized
[ERR] [EntryPoint.cs:41(Process)]
System.Exception: No Database Loaded
   at StringReloads.Engine.SRL.get_CurrentDatabase()
   at StringReloads.Engine.Match.BasicMatch.MatchString(String String)
   at StringReloads.Engine.SRL.MatchString(IMatch This, String String)
   at StringReloads.Engine.SRL.ProcessString(String String)
   at StringReloads.Engine.SRL.ProcessString(CString pString)
   at StringReloads.EntryPoint.Process(Void* Value)
```
As you can see, this is the error.
You tried translate the game but as he said: No database loaded.
This mean you tried translate the game without give to the SRL any translation.
You can use the ![https://github.com/marcussacana/StringReloads/blob/DotNetFramework/Help/LST%20Generator.rar](LST Generator) tool to create the .lst files to the SRL, then move to the SRL working directory.
(You will need install the UnisonShiftManager plugin to extract the game text)

**Comment by hacker123-321** [comment]
It happened an error again. Can you use discord? I can make friends with you.  we need to talk more carefully

**Comment by marcussacana** [comment]
Delete the Cache.srl file and try again.
If not works then you put the .lst file in the wrong directory.

**Comment by hacker123-321** [comment]
Firstly i extract file data.pac with unisonshift managers 
I created file string.lst from file TEXT.DAT
I put the file .lst in the folder reload

**Comment by marcussacana** [comment]
You must left the .lst file in the working directory of the SRL, in your case, as you can see in the log:
```
[DBG] Working Directory: C:\Users\huy\Desktop\shin-neko ～再会した妹との新たな関係～\StringReloads
```
after that just delete the Cache.srl and translate the lines in the Strings.lst

**Comment by hacker123-321** [comment]
i delete the cacher.srl and translate one line in the String.lst, But it is still japanese in game

**Comment by marcussacana** [comment]
But the crash stopped, rigth?
If isn't translate is just a missmatch in the .lst and the game dialogue,
use the Log to see the "Input" content and compare with the one in your .lst file.
the SRL must have the exact copy of the text to translate it.

**Comment by hacker123-321** [comment]
you can see it 
https://huyvuvi123-gmail.tinytake.com/tt/NDYwNDAwMF8xNDU5NTE5MA

**Comment by hacker123-321** [comment]
I was successful. it was great

**Comment by hacker123-321** [comment]
I ran into another problem, it was about the fonts
I cannot convert it to arial font

**Comment by hacker123-321** [comment]
you can guide move font

**Comment by marcussacana** [comment]
Enable the CreateFont/CreateFontIndirect hook, we have 4 hooks, one of then will works.
Then in the end of the SRL.ini you can see a Gothic Modded, change to Arial

**Comment by hacker123-321** [comment]
after change font from ＭＳ 明朝 to arial
it have error as:
it is true
![true](https://user-images.githubusercontent.com/68116972/92392956-4b82ee80-f149-11ea-9d3a-ffc1fd69a2c1.PNG)
but it is
![error](https://user-images.githubusercontent.com/68116972/92392989-58074700-f149-11ea-955a-433a5971cfc5.png)
![Error2](https://user-images.githubusercontent.com/68116972/92392997-5d649180-f149-11ea-9d9d-c80dcea73238.PNG)

**Comment by marcussacana** [comment]
Take a look at this: https://github.com/marcussacana/Specific-Games/blob/master/Daitoshokan%20no%20Hitsujikai.rar
What you need is create a custom Chars.lst file with a remap of all characters of your lang to a japanese one, then put in the working directory of the SRL.
After that you can give a try enabling the TextOutA + UndoRemap to make your language characters work.
If that don't work then you will need create a custom font with all characters in the Chars.lst modified to look like your language character, then use the CreateFont hook to force the game use your modded font.

**Comment by hacker123-321** [comment]
are there any wings to know which special characters will correspond to which Japanese characters?
Or have to try each letter

**Comment by marcussacana** [comment]
Not really, but usually the half-width characters are the best to replace

**Comment by marcussacana** [comment]
If you need anything more you can re-open the issue.
