### ISSUE TITLE
font program

### ISSUE THREAD

**Issue by hacker123-321** [marcussacana/StringReloads#6]
after i creater new font has char vietnamese corresponding char of SJIS but in game, chars vietnamese are gone in location of it

**Comment by marcussacana** [comment]
I really don't get it.

**Comment by hacker123-321** [comment]
I created the font like:
![Screenshot (5) - Copy](https://user-images.githubusercontent.com/68116972/93107635-142db800-f6dc-11ea-910d-f6c77679062f.png)
example char ｫ = ạ
but in game char hạn => hn

**Comment by marcussacana** [comment]
Okay, That I get, but after that, what the problem?

**Comment by hacker123-321** [comment]
Problem is like
I want to display "có một vụ tai nạn trong con hẻm"
In game it is  "c mt v ti nn trong con hm"

**Comment by marcussacana** [comment]
you're using the SRL rigth?
You edited the Chars.lst to match with your font?
