### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by s911110** [marcussacana/StringReloads#7]
![J@A(`U 4`T J}P2XWGIIE_P](https://user-images.githubusercontent.com/15063790/94769375-7a0c8600-03e4-11eb-9e4a-c233ffb399e7.png)
l get two errors
```
Error	CS0246	The type or namespace name 'CoInitializeDelegate' could not be found (are you missing a using directive or an assembly reference?)	StringReloads	C:\StringReloads-master\StringReloads\Hook\Win32\CoInitialize.cs	9	Active
Error	CS1955	Non-invocable member 'Hook<CoInitializeDelegate>.Bypass' cannot be used like a method.	StringReloads	C:\StringReloads-master\StringReloads\Hook\Win32\CoInitialize.cs	23	Active
```
how can i solve this problem ？
Visual Studio Version 16.7.5

**Comment by s911110** [comment]
yet now there was no erros。
After successful build I found that SRLWrapper.dll has no Export and can‘t work。
**DllExport set**
![QQ截图20201002131804](https://user-images.githubusercontent.com/15063790/94890704-95de5d80-04b2-11eb-8cd4-531d2a183a8d.png)
![QQ截图20201002132027](https://user-images.githubusercontent.com/15063790/94890730-ab538780-04b2-11eb-8de8-b19a7ddb362d.png)

[SRLWrapper.zip](https://github.com/marcussacana/StringReloads/files/5316103/SRLWrapper.zip)

**Comment by marcussacana** [comment]
any build error is showed?

**Comment by s911110** [comment]
I’m already done,just get a wrong directory.
at first l find in **StringReloads-master\SRLDebugger\obj\**  dll there is no Export
then i find in **StringReloads-master\SRLDebugger\bin\x86** dll there is no problem.
