### ISSUE TITLE
AdvHD Incompatible Game

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/StringReloads#8]
Hello marcus, i was wondering if you can help me to create a mod font for the next game:

https://vndb.org/v25784

I try to enable the autoinstall featured (with the x64 SRLwrapper) but the game just start and doesn't do anything more (I even follow the tutorial video), and with the x32 the game crash at the initial launch. The game uses ADVHD engine!

Thanks in advance!

**Comment by marcussacana** [comment]
This game is x64? I never saw a AdvHD game with x64 binaries...
Anyway, show me the steps that you did to try install it, maybe you did something wrong.

**Comment by Tfausx** [comment]
First i downloaded this (from this repository):

![imagen](https://user-images.githubusercontent.com/29191836/116907098-7f021400-ac17-11eb-8363-0669b28c4faf.png)

I move both, SRL.ini and SRLWrapper.dll to the game folder (where .exe is), then i rename SRLWrapper.dll to d3d9.dll, open the SRL.ini and set the AutoInstall=true, then i initialize the game but crash at startup (with the x32 SRLWrapper.dll), with the x64, doesn't start at all

This is how it looks my game folder:

![imagen](https://user-images.githubusercontent.com/29191836/116907454-f637a800-ac17-11eb-813a-c72f79205f6c.png)

**Comment by marcussacana** [comment]
Your game is original? Becaue that files 'protect', maybe the SRL isn't working because of the game DRM.

**Comment by Tfausx** [comment]
No, the game it's a cracked release, even if i removed those two protect.exe and protect.x86 the game starts without problem

**Comment by marcussacana** [comment]
Send a download link of this game to my email and I will take a look when I can

**Comment by Tfausx** [comment]
Sent it

**Comment by marcussacana** [comment]
It's working basically, you just need to use the dxgi.dll wrapper instead d3d9.dll or something like that
![image](https://user-images.githubusercontent.com/10576957/117021163-7c61f600-accd-11eb-9ca7-5d8056c17ca3.png)

**Comment by marcussacana** [comment]
You should download the last version anyway, I fixed a non related bug.

**Comment by Tfausx** [comment]
i downloaded and renamed the SRLwrapper.dll to dxgi.dll but now the game open and close inmediately, i'm missing something in the SRL.ini? Some parameter or something like that (i just change the autoinstall to true)

---
Or perhaps i'm misunderstanding all and i need to download the entire branch and compile by myselft the dll?

Sorry for the trouble and thanks for your patience!

**Comment by marcussacana** [comment]
You used the x32/x86 version, right?
What is you operating system? (with version)
maybe you have something like a AV trrigering?

**Comment by marcussacana** [comment]
do you have the .net framework installed as well?

**Comment by Tfausx** [comment]
-You used the x32/x86 version, right?
Yep
----
-What is you operating system? (with version)
Windows 10 Version 1909
----
-maybe you have something like a AV trrigering?
No, i don't use AV at all and the windows defender doesn't block anything
----
do you have the .net framework installed as well?
Yes, all of them.
----
It's weird, the game starts without problems without the SRL, but when i activated, just open and close, i'm gonna try latter with another game with this engine and company, if not work, will try in another computer the next week.

---
PD: It's not possible to you upload me your "modded" archives to try in my computer?

Thanks in advance!

**Comment by marcussacana** [comment]
Maybe is because you didn't created any .lst file?
The SRL only works when he have a database to initalize.
[data.rar.zip](https://github.com/marcussacana/StringReloads/files/6424483/data.rar.zip)

**Comment by Tfausx** [comment]
seems like that was the problem, with the .rar you sent me all works fine! Just one last question, what option (in SRL.ini) i have to enable to dump the dialogs of the game inside of strings.lst file?

**Comment by marcussacana** [comment]
the `Dump` but I didn't recommend to this game, you can use my LSTGenerator https://github.com/marcussacana/StringReloads/blob/DotNetFramework/Help/LST%20Generator.rar
Using the SacanaWrapper this tool will dump to you the .ws2 scripts that you can extract with garbro, after that you just need copy the .lst files to the SRL.
